### ISSUE TITLE
Stop button does not always work on the first click.

### ISSUE THREAD

**Issue by mgmmgm14** [talonvoice/noise#12]
I made this video so you can better see the problem of the stop button, first tried it in incognito mode in Chrome on Mac, then I return to normal mode (with previously recorded noises) and it works badly on the first sound he recorded, then works  all right until I changed the tab, and when I come back it works badly again
It happened to me in mozilla and in Chrome on both Mac El capitán and Windows 7, easily reproducible, Even in incognito mode.
opening the inspection console causes the stop button to fail way more often, but the record button always works on the first attempt 
I posted a video on the slack Channel of #noise in which you can clearly see the behavior

**Comment by nickvisut** [comment]
@mgmmgm14 thanks for report and video; lmk if fully fixed
